export const siteConfig = {
  name: 'Cozuro Tools',
  url: 'https://cozurotools.com',
  description:
    'Free browser-based image and file tools. Compress images, convert formats — everything runs locally, your files never leave your device.',
  twitterHandle: '@cozurotools',
  tools: [
    {
      id: 'image-compressor',
      href: '/tools/image-compressor',
      icon: 'ImageDown',
      color: 'from-sky-500 to-blue-600',
      bgLight: 'bg-sky-50',
      bgDark: 'dark:bg-sky-950/30',
      iconColor: 'text-sky-600 dark:text-sky-400',
    },
    {
      id: 'webp-converter',
      href: '/tools/webp-converter',
      icon: 'RefreshCw',
      color: 'from-violet-500 to-purple-600',
      bgLight: 'bg-violet-50',
      bgDark: 'dark:bg-violet-950/30',
      iconColor: 'text-violet-600 dark:text-violet-400',
    },
    {
      id: 'jpg-to-pdf',
      href: '/tools/jpg-to-pdf',
      icon: 'FileImage',
      color: 'from-rose-500 to-pink-600',
      bgLight: 'bg-rose-50',
      bgDark: 'dark:bg-rose-950/30',
      iconColor: 'text-rose-600 dark:text-rose-400',
    },
    {
      id: 'pdf-compressor',
      href: '/tools/pdf-compressor',
      icon: 'FileDown',
      color: 'from-amber-500 to-orange-600',
      bgLight: 'bg-amber-50',
      bgDark: 'dark:bg-amber-950/30',
      iconColor: 'text-amber-600 dark:text-amber-400',
    },
    {
      id: 'pdf-to-jpg',
      href: '/tools/pdf-to-jpg',
      icon: 'Images',
      color: 'from-emerald-500 to-teal-600',
      bgLight: 'bg-emerald-50',
      bgDark: 'dark:bg-emerald-950/30',
      iconColor: 'text-emerald-600 dark:text-emerald-400',
    },
    {
      id: 'merge-pdf',
      href: '/tools/merge-pdf',
      icon: 'Combine',
      color: 'from-indigo-500 to-blue-700',
      bgLight: 'bg-indigo-50',
      bgDark: 'dark:bg-indigo-950/30',
      iconColor: 'text-indigo-600 dark:text-indigo-400',
    },
  ],
} as const;

export type ToolId = (typeof siteConfig.tools)[number]['id'];
